### ISSUE TITLE
Don't trigger a warning when pressing different restricted keys

### ISSUE THREAD

**Issue by liangkarl** [m4xshen/hardtime.nvim#1]
I have noticed that when I repeatedly hit certain restricted keys, such as "jkjk...", I receive a warning from `hardtime` that I have pressed the keys too quickly. However, I believe that this warning should only be given if I repeatedly press the same key, such as "jjjj...". It seems unreasonable to receive a warning for pressing different combinations of restricted keys, as some of these combinations may be still necessary. I am unsure if this is a reasonable idea or not. Correct me if there is something wrong.
Anyway, are there any options available to avoid this problem? Thanks.

**Comment by m4xshen** [comment]
If the warning is only triggered when pressing same keys, user can use something like `h` `k` `h` `k` `h` `k` to move. However I also think it is great to have an option to change this behavior. I'll add this in the future.

**Comment by m4xshen** [comment]
You can now set the option `allow_different_key = true` to solve your problem!
