### ISSUE TITLE
Detect more complicated actions / commands

### ISSUE THREAD

**Issue by smjonas** [m4xshen/hardtime.nvim#10]
Thanks for the plugin! While I haven't tried it myself, it seems like the scope of this plugin is currently mostly focused around Vim movements such as `hjkl`. In the past, there have been other requests for a plugin that can detect more complex actions / Vim motions and suggest better alternatives. So my first question is: is that even something you would consider for this plugin or should it stay relatively simple in scope?

As an example, I could imagine things like:
- if the user uses `daw` + `i`, suggest `caw` instead
- `$` + `a` => `A`; `^` + `i` => `I`; `y$` => `Y` (`y$` has been remapped to `Y` by default in Neovim)

While the above suggestions should be relatively simple to implement, there are many many others that can get arbitrarily more complicated since they require analyzing a part of the buffer's edit history (i.e. the last `n` changes). 
Examples:
- the user changes `ex|ample` (`|` is the cursor position) to `sample` but uses `ciwsample` => suggest `cbs` instead
- the user appends the same string to multiple consecutive lines (e.g. with dot repeat) => suggest to use `<c-i>` (blockwise visual mode) or the norm command

One could even suggest plugins to simplify certain actions:
- the user changes `local x` to `-- local x` in a Lua file but enters insert mode (e.g. `I-- <esc>`) => suggest a commenting plugin such as `mini.comment`
- the user changes `some |word here` to `some (word)| here` but enters insert mode (e.g. `i(<esc>ea)<esc>`) => suggest a surrounding plugin such as `nvim-surround`

Ideally, it should be possible to dismiss certain suggestions in which case it won't be shown for the current session or never again. Let me know if you could imagine such suggestions as part of the plugin or not! :)

**Comment by m4xshen** [comment]
Thanks for your long feedback! I would definitely consider to add more complicated actions for detection. My first goal is to add the general delete + insert motion into change motion.

As for:
>  `ciwsample` => suggest `cbs` instead

This kind of detection is more complicated and I'll try to implement after finishing the first one.

btw these two are already in hardtime.nvim:

> `$` + `a` => `A`; `^` + `i` => `I`

**Comment by juiceDeLemon** [comment]
maybe f<char>h should trigger a warning "Use t<char> instead of f<char>h" and the reverse ("F<char>l" and "t<char>l" and "T<char>h")

**Comment by juiceDeLemon** [comment]
ah I just thought of more. "diwi" should be shortened to "ciw". basically "d something i" -> "c something". I don't know the operator mode would work though.

**Comment by m4xshen** [comment]
> My first goal is to add the general delete + insert motion into change motion.

Yeah this is just what I want to do first. Thanks!

**Comment by m4xshen** [comment]
You can now get the hints about delete + insert and f/F/t/T in the latest version! You can also write your own hints in the config. See [examples](https://github.com/m4xshen/hardtime.nvim#-configuration)
