### ISSUE TITLE
Custom hint for <BS> or <BSpace>

### ISSUE THREAD

**Issue by supportcdl** [m4xshen/hardtime.nvim#104]
Firstly, thanks for making this amazing plugin, appreciate it!

This is more for the hardtime community: I have been playing around with custom opts and I was wondering if anyone has managed to create a custom hint for the backspace (\<BS\> or \<BSpace\>)? This is my terrible attempt:

```
    opts = {
      hints = {
        ["[<BSpace>]"] = {
          message = function(keys)
             return "Don't use BSpace."
          end,
          length = 1,
        },
      },
    },
```

**Comment by m4xshen** [comment]
HI, @supportcdl you can config like this:

```lua
["<BS>"] = {
   message = function()
      return "Don't use <BS>."
   end,
   length = 4,
},
```

However this only works in normal mode. Hardtime currently only supports hints in normal mode
