### ISSUE TITLE
Invisible hint messages when showmode is enabled

### ISSUE THREAD

**Issue by thimc** [m4xshen/hardtime.nvim#11]
Hi,

Lovely plugin, thanks for sharing! After a few minutes of playing around I noticed that when the `set showmode` setting is enabled, the hint messages are pretty much invisible.

I haven't really dug in to the code yet to see how these are printed but I would assume it's the regular `print()` function that is used. Perhaps one way to solve this would be to display the messages in a floating window?

**Comment by m4xshen** [comment]
I can't reproduce your issue. Actually the `showmode` option is on by default in Neovim. Could you please provide more information?

**Comment by thimc** [comment]
That's weird, I specifically tried this with the `c$` motion which should say something along the lines of "Use C instead of c$".

I may have to try this with a default config of Neovim to verify that there isn't anything else that does this

**Comment by m4xshen** [comment]
Hey did you find out waht causes the problem?

**Comment by thimc** [comment]
No, sadly not. I haven't been able to find what's causing it. I did try a vanilla neovim config with just packer and your plugin but that didn't help at all.

**Comment by m4xshen** [comment]
Could you provide code that you setup this plugin?

**Comment by thimc** [comment]
Well sure, I use the snippet provided in the README. Besides that there's packer but I seriously doubt that is the thing causing this.

`require("hardtime").setup()`

**Comment by m4xshen** [comment]
So it is not the problem of `showmode`?

**Comment by m4xshen** [comment]
> I get the message at the bottom of the screen for all other actions besides those that enters INSERT or VISUAL mode.

So you got hint messages for `use - instead of k^` but not `use C instead of c$`. Am I right?

**Comment by m4xshen** [comment]
Can you see the warning message when pressing `j` repeatedly?

**Comment by thimc** [comment]
Yes

**Comment by m4xshen** [comment]
What Neovim version are you using?

**Comment by ErenKyojin** [comment]
Same issue here! With version 0.9.1-1 of neovim.

**Comment by m4xshen** [comment]
@ErenKyojin did you try out hardtime.nvim without other plugin and config?

**Comment by ErenKyojin** [comment]
> @ErenKyojin did you try out hardtime.nvim without other plugin and config?

I did, and the issue still persists (with lazy)

**Comment by fynnfluegge** [comment]
Facing the same issue. Notifications are visible, hints are invisible. The other way round would be fine for me 😅

**Comment by m4xshen** [comment]
The problem is that the mode message replaces the hint message.
Here are some solutions:
1. Display the mode on status line and set `showmode` to false. You can do this with some statusline plugin such as lualine.nvim.
2. Set the `cmdheight` to 2 so that the hint message won't be replaced by mode message.
3. Use nvim-notify to display hint messages on the right top corner instead of commandline.
