### ISSUE TITLE
Ability to disable certain file/buffer types

### ISSUE THREAD

**Issue by tedkulp** [m4xshen/hardtime.nvim#12]
I love this plugin, but it doesn't always work in every situation.

For example: neogit doesn't really support using 3j instead of jj. Or: neotree technically works, but it's really not ideal when you're digging through sub-directories to have to stop and make sure you hit have proper syntax.

Sure, you can make sure you disable/re-enable, but if it gets to be too much of a hassle, then it just has to be disabled permanently.

**Comment by m4xshen** [comment]
You can disable certain filetypes with `disabled_filetypes` option.
Its default value is:
```
disabled_filetypes = { "qf", "netrw", "NvimTree", "lazy", "mason" },
```

**Comment by tedkulp** [comment]
I'm so sorry about that. I swear I looked at that list of options like 5 times and my brain just passed over it every single time.

Thank you, and thanks again for cool plugin!
