### ISSUE TITLE
Messes up behaviour of mini.jump2d

### ISSUE THREAD

**Issue by makew0rld** [m4xshen/hardtime.nvim#127]
**Describe the bug**

With both [mini.jump2d](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-jump2d.md) and this plugin installed, the normal behaviour of mini.jump2d is changed. I have to redo the two jump keys every time, instead of just having to do the process once like normal. It's like it gets interrupted or restarted.

**Config options**

```lua
  {
    'm4xshen/hardtime.nvim',
    dependencies = { 'MunifTanjim/nui.nvim' },
    opts = {},
  }
```

**To Reproduce**
1. Install mini.jump2d
2. Install hardtime.nvim
3. Hit enter, then two letter keys to jump to a location
4. Observe that you have to do this once more for it to work

(I am working off of kickstart.nvim as my initial config but I'm not sure if that's relevant)

**Expected behavior**

mini.jump2d works like normal.

**Additional context**

This issue was first reported by someone else in a discussion: https://github.com/m4xshen/hardtime.nvim/discussions/102

**Comment by SwayKh** [comment]
I also have this same issue, and additionally having hardtime.nvim and MiniFiles also causes issues, with closing and reopening MiniFiles window.

**Comment by m4xshen** [comment]
@makew0rld you can now update hardtime.nvim to latest version. mini.jump2d should works fine now!

**Comment by makew0rld** [comment]
Can confirm it works like normal now, thanks!
