### ISSUE TITLE
What is the useful of  resetting_keys section ?

### ISSUE THREAD

**Issue by Meigumikato** [m4xshen/hardtime.nvim#13]
I use yy (double y)  to lazy load  yank.nvim plugin, but when hardtime.nvim set resetting_keys section for `y` key that lead yank.nvim can not normal loaded. When i set resetting_keys section empty, it can good work.

**Comment by Meigumikato** [comment]
I try change resetting_keys section `y` key effective mode to only `v` then i can use `yy` success lazy load my yank.nvim plugin in `n` mode. The resetting_keys are normal work except `y` and `p`  when i have yank.nvim plugin. I think those plugin have some conflict, but i can not find this problem.

**Comment by m4xshen** [comment]
Could you please update to the latest version and try whether it works without changing the resetting_keys? I just fixed the issue yesterday.

**Comment by Meigumikato** [comment]
I update to lastest, now it's work fine.
