### ISSUE TITLE
not enabled at first when doing `nvim <filename>` with `lazy.nvim`

### ISSUE THREAD

**Issue by llllvvuu** [m4xshen/hardtime.nvim#19]
To reproduce:
```lua
{
  "m4xshen/hardtime.nvim",
  opts = {}
},
```
open `nvim` from the command-line like `nvim <filename>`. `hardtime.nvim` will not start until you open another buffer. Probably because of this:
https://github.com/m4xshen/hardtime.nvim/blob/main/lua/hardtime/init.lua#L153

**Comment by m4xshen** [comment]
I can't reproduce the issue. Are you using the latest version of hardtime.nvim?



> because of this:
> https://github.com/m4xshen/hardtime.nvim/blob/main/lua/hardtime/init.lua#L153

But I think the `BufNew` event is also triggered with `nvim <filename>`
