### ISSUE TITLE
Not Getting Recommendations

### ISSUE THREAD

**Issue by jrock2004** [m4xshen/hardtime.nvim#2]
So maybe this has something to do with another plugin, but I was testing hitting the down arrow. I was expecting the hey there is a better way, but it never tells me the better way

![image](https://github.com/m4xshen/hardtime.nvim/assets/655716/d19151f1-a40c-4e8b-92e7-47a51aa39d5b)

[Config can be found here](https://github.com/jrock2004/dotfiles/blob/68137447f8f7e3a1132489be6b968c61834a8556/files/.config/lvim/config.lua#L196)

```
{
    "m4xshen/hardtime.nvim",
    opts = {
      hint = true,
    }
  },
```

**Comment by delightfulabyss** [comment]
Seconding this. I'm using the default config and I'm not getting any of the recommendations specified in the readme.

**Comment by m4xshen** [comment]
> Seconding this. I'm using the default config and I'm not getting any of the recommendations specified in the readme.

Do you set the `'cmdheight'` option to zero or use plugin like noice.nvim?

**Comment by delightfulabyss** [comment]
> > Seconding this. I'm using the default config and I'm not getting any of the recommendations specified in the readme.
> 
> Do you set the `'cmdheight'` option to zero or use plugin like noice.nvim?

Nope, I just use the regular command line.

**Comment by delightfulabyss** [comment]
Apologies, I am getting the hints now. I think it was an issue with my setup.

**Comment by jrock2004** [comment]
> Apologies, I am getting the hints now. I think it was an issue with my setup.

What did you do to figure it out?

**Comment by jrock2004** [comment]
Just tried with my https://www.lazyvim.org config and it does not work at all for me

**Comment by m4xshen** [comment]
Cloud you please try to disable the noice.nvim and see whether it works?

**Comment by jrock2004** [comment]
@m4xshen disabled noice and still does not work

**Comment by jrock2004** [comment]
Interesting fine with my lazyvim if I do `shift+v` then I hit j a bunch of times I get the blockage

**Comment by m4xshen** [comment]
It doesn't block the repeated keys in the normal mode?

**Comment by jrock2004** [comment]
Nope

**Comment by jrock2004** [comment]
Updated the config to the following and now its worse and nothing works

```
return {
  "m4xshen/hardtime.nvim",
  config = function()
    vim.notify = require("notify")
  end,
  opts = {
    disable_mouse = false,
    hint = true,
  },
}
```

**Comment by m4xshen** [comment]
You should put `vim.notify = require("notify")` after where the notify is installed.

**Comment by m4xshen** [comment]
Notice that you should set `vim.notify = require("notify")` at where you install nvim-notify.
