### ISSUE TITLE
No way to re-enable the arrow keys

### ISSUE THREAD

**Issue by KaitlynEthylia** [m4xshen/hardtime.nvim#23]
I want to be able to use the arrow keys to move around, but they are disabled by default, and it no longer seems possible to change this

Previously, I set `disabled_keys` to an empty table and that worked, but it no longer does, I've also tried
```lua
disabled_keys = {
	["<UP>"] = nil,
	["<DOWN>"] = nil,
	["<LEFT>"] = nil,
	["<RIGHT>"] = nil,
}
```
but that did not work

**Comment by m4xshen** [comment]
You should change it to:

```lua
disabled_keys = {
	["<UP>"] = {},
	["<DOWN>"] = {},
	["<LEFT>"] = {},
	["<RIGHT>"] = {},
}
```

See the [readme](https://github.com/m4xshen/hardtime.nvim#-configuration) for more information.
