### ISSUE TITLE
Restricting <UP>, <DOWN>, <LEFT>, <RIGHT> does not work.

### ISSUE THREAD

**Issue by Zhaith-Izaliel** [m4xshen/hardtime.nvim#29]
Hi!

**Describe the bug**
Setting up `<UP>`, `<DOWN>`, `<LEFT>` or `<RIGHT>` as restricted does not restrict them.

**To Reproduce**

1. Enable `<UP>`, `<DOWN>`, `<LEFT>` or `<RIGHT>` in `setup.disabled_keys`
2. Restrict `<UP>`, `<DOWN>`, `<LEFT>` or `<RIGHT>` in `setup.restricted_keys`
3. Open a file
4. Move around with `<UP>`, `<DOWN>`, `<LEFT>` or `<RIGHT>`
5. See no notification popping up or restriction applied on `<UP>`, `<DOWN>`, `<LEFT>` or `<RIGHT>`

**Expected behavior**
Setting up `<UP>`, `<DOWN>`, `<LEFT>` or `<RIGHT>` in `setup.restricted_keys` should trigger the count mechanism.

**Additional context**
Here is my configuration triggering the issue:

```lua
-- Hardtime
require('hardtime').setup {
  allow_different_key = true,
  enabled = true;
  restricted_keys = {
    ['<UP>'] = { 'n', 'x' },
    ['<DOWN>'] = { 'n', 'x' },
    ['<LEFT>'] = { 'n', 'x' },
    ['<RIGHT>'] = {'n', 'x' },
    ['+'] = {},
    ['-'] = {},
    ['g<UP>'] = { 'n', 'x' },
    ['g<DOWN>'] = { 'n', 'x' },
  },
  disabled_keys = {
    ['<UP>'] = {},
    ['<DOWN>'] = {},
    ['<LEFT>'] = {},
    ['<RIGHT>'] = {},
  },
}
```

Have a nice day!

**Comment by m4xshen** [comment]
Thanks for the feedback!

**Comment by m4xshen** [comment]
@Zhaith-Izaliel I just refactored the code of the plugin and I found that my old config contained incorrect key name. Now you should use `<Up> <Down> <Left> <Right>` instead of `<UP> <DOWN> <LEFT> <RIGHT>`.
