### ISSUE TITLE
J and K repeats are not blocked

### ISSUE THREAD

**Issue by delightfulabyss** [m4xshen/hardtime.nvim#3]
H and L repeats are being blocked as expected but J and K repeats are being allowed.

Using Neovim 0.9.0 and Ubuntu 22.04.

{
	"m4xshen/hardtime.nvim",
	opts = {},
}

[Config is here](https://github.com/delightfulabyss/dotfiles/tree/main/private_dot_config/nvim)

**Comment by m4xshen** [comment]
I just added `gk` and `gj` to the `restricted_keys`. Update the plugin and the problem should be solved.

**Comment by PeretEtienne** [comment]
Despite `gk` and `gj` being added to the `restricted_keys`, I am still able to spam those keys with neovim. Do you know what could cause this or how I could investigate this problem ? Thx

**Comment by m4xshen** [comment]
Hi @PeretEtienne, have you tried https://github.com/m4xshen/hardtime.nvim/issues/31#issuecomment-1685762701?

**Comment by PeretEtienne** [comment]
Just tried it and it looks like the colon in "v:count" is interpreted and all it does is launching me a command with "count || mode(1)[0:1] == "no" ? "j" : "gj"' as content. I am on Lazyvim btw, I don't know if it makes a difference

**Comment by m4xshen** [comment]
> I don't know what you did in recent patches but now my "j" and "k" are now well restricted. Seems like in between I had time to take bad habits haha. Time to have a hardtime 👍 Thx

Nice! Hope u enjoy the hardtime 😆
