### ISSUE TITLE
j/k not repeating when using NvChad distro

### ISSUE THREAD

**Issue by nooproblem** [m4xshen/hardtime.nvim#31]
Firstly, thanks for making this amazing plugin! I am using the NvChad distro, and I have installed hardtime.nvim using Lazy and set lazy = false so the plugin is enabled on startup. I have run into a odd situation where it hardtime.nvim does not pick up j/k repeating. I can fix this issue by running ":Hardtime toggle" twice ( or ":Hardtime enable" and then ":Hardtime disable") in order to switch hardtime.nvim off/on. Any thoughts on why this might occurring would be appreciated!

**Comment by m4xshen** [comment]
Could you try to remove the `lazy = false` and see whether it works?

**Comment by m4xshen** [comment]
Does hardtime.nvim not pick up only j/k repeating? How about other keys?

**Comment by nosduco** [comment]
Also running NvChad and am having this issue. I am wondering if it is due to NvChad's j/k mapping https://github.com/NvChad/NvChad/blob/v2.0/lua/core/mappings.lua#L40

**Comment by nooproblem** [comment]
Thank you!
