### ISSUE TITLE
Feature: disable every keys individually

### ISSUE THREAD

**Issue by mostafaqanbaryan** [m4xshen/hardtime.nvim#36]
**Describe the bug**
First, thank you for your great plugin!
If you press `j` and then `k`,  and then again `j`, `k` would be disabled too.
But these keys are different and if I hit the limit on using one of them, others should be able to work.

**Config options**
Default

**To Reproduce**
Explained in the description

**Expected behavior**
Each key's timeout should be separated

**Comment by m4xshen** [comment]
Did you try out setting `allow_different_key = true`? This will produce a similar effect of what you want.

**Comment by mostafaqanbaryan** [comment]
I've completely missed that
Thank you!
