### ISSUE TITLE
Feature: Swap to `restriction_mode = 'hint'` when running a macro

### ISSUE THREAD

**Issue by vince-carpino** [m4xshen/hardtime.nvim#39]
This plugin has been very helpful to say the least, especially whilst in `block` mode.

However, I think it would be great if there was an option/ability to swap to `hint` mode when running a macro, since the blocking can mess up the result, especially if repeated multiple times.

I don't even know if this is possible, so if there is a preferred workaround, please let me know.

**Comment by m4xshen** [comment]
Thanks for the suggestion. This is really useful!

**Comment by m4xshen** [comment]
My approach is just completely disable hardtime.nvim when executing macro.
