### ISSUE TITLE
Feature: `cond` function

### ISSUE THREAD

**Issue by dtomvan** [m4xshen/hardtime.nvim#44]
I don't want hardtime in the way when recording macros, at all. The macro
pressure is enough, you know :)

My solution is at follows: introduce a `cond` configuration function. It could
be used as follows.

```lua
require('hardtime').setup {
    cond = function(_key)
        return #vim.fn.reg_recording() == 0
    end,
}
```

**Comment by m4xshen** [comment]
I already consider the [condition of executing macro](https://github.com/m4xshen/hardtime.nvim/blob/main/lua/hardtime/init.lua#L26). You can just open a pr to add the condition of recording. I think it is much simpler.

**Comment by dtomvan** [comment]
Alright, but I wanted to consider any other reasons to specify a condition. What if you wanted to disable it for any other non builtin reason? Then `cond` could be used.

**Comment by m4xshen** [comment]
I understand your concern, but now I don't think of any other reasons to disable it.

**Comment by dtomvan** [comment]
Alright, PR'ing somewhere tonight, then 😅
