### ISSUE TITLE
Do not detect “<MouseMove>” as “ve>”

### ISSUE THREAD

**Issue by mochaaP** [m4xshen/hardtime.nvim#49]
When `vim.opt.mousemoveevent = true`:

![image](https://github.com/m4xshen/hardtime.nvim/assets/21154023/690adfb0-0ec0-4193-9a63-4795db179473)

(Example use case: <https://github.com/akinsho/bufferline.nvim/blob/6ecd37e0fa8b156099daedd2191130e083fb1490/lua/bufferline/hover.lua#L35>)

This should not be matched as `ve>`.

**Comment by m4xshen** [comment]
Thanks for the feedback!
