### ISSUE TITLE
The recent update that addresses gk and gj 

### ISSUE THREAD

**Issue by directormac** [m4xshen/hardtime.nvim#5]
[LazyVim Discussion Reference](https://github.com/LazyVim/LazyVim/discussions/936)
![image](https://github.com/m4xshen/hardtime.nvim/assets/5866196/e13a87c5-28a3-4ae1-b02c-94871ca9de93)

**Comment by directormac** [comment]
I removed the "d" keys on hint and resetting keys did the trick for now but hoing youd have a fiix on it.

**Comment by m4xshen** [comment]
Please try out the latest version and try whether it works now.

**Comment by directormac** [comment]
> 

The default config works smooth now, but the "gk" and "gj" isn't triggering the hardtime for some unknown reasons, was working sometimes like a week ago.

**Comment by m4xshen** [comment]
Can you provide your mapping of gj and gk? Or are you using the default config of LazyVim?

**Comment by m4xshen** [comment]
Can you provide your mapping of gj and gk? Or are you using the default config of LazyVim?

**Comment by directormac** [comment]
The default one from lazyvim, i believe this is it.

```lua
-- better up/down
map({ "n", "x" }, "j", "v:count == 0 ? 'gj' : 'j'", { expr = true, silent = true })
map({ "n", "x" }, "k", "v:count == 0 ? 'gk' : 'k'", { expr = true, silent = true })
```

**Comment by m4xshen** [comment]
This mapping works for me. Do you have any other config that might override this?

**Comment by directormac** [comment]
I will check it out soon and setup a fresh install with lazyvim and only use your plugin.

**Comment by m4xshen** [comment]
Thanks a lot.

**Comment by directormac** [comment]
d and key are doing its job, it's just not showing the whichkey menu, maybe its because of the delays set on which-key by default at lazyvim i am not sure tho, Thank you for fixing that! only solution to gk and gj is rebind it i think in keymaps for us lazyvim users. 🤖

**Comment by m4xshen** [comment]
Do you set the keymap before the plugin's setup? If yes, try to set the keymap after that.

**Comment by lbiaggi** [comment]
@m4xshen, just to let you know, I'm facing the same problem.

**Comment by m4xshen** [comment]
@directormac please try out the latest version. Thanks.

**Comment by lbiaggi** [comment]
> Do you mean that gj and gk don't trigger hardtime? Do you also use LazyVim or use custom map for j and k?

I just use a custom map
```
vim.keymap.set("n", "k", "v:count == 0 ? 'gk' : 'k'", { noremap = true, expr = true, silent = true })
vim.keymap.set("n", "j", "v:count == 0 ? 'gj' : 'j'", { noremap = true, expr = true, silent = true })

**Comment by m4xshen** [comment]
> 
> I just use a custom map
> 
> ```
> vim.keymap.set("n", "k", "v:count == 0 ? 'gk' : 'k'", { noremap = true, expr = true, silent = true })
> vim.keymap.set("n", "j", "v:count == 0 ? 'gj' : 'j'", { noremap = true, expr = true, silent = true })
> ```

After setting the keymap, the j and k don't trigger hardtime?

**Comment by thenbe** [comment]
> > I just use a custom map
> > ```
> > vim.keymap.set("n", "k", "v:count == 0 ? 'gk' : 'k'", { noremap = true, expr = true, silent = true })
> > vim.keymap.set("n", "j", "v:count == 0 ? 'gj' : 'j'", { noremap = true, expr = true, silent = true })
> > ```
> 
> After setting the keymap, the j and k don't trigger hardtime?

Trying out hardline for the first time now. Hardtime fails to trigger for `gj`/`gk`.

**Comment by m4xshen** [comment]
> Trying out hardline for the first time now. Hardtime fails to trigger with this keymap.

What Neovim version are you using? I can't reproduce the issue.

**Comment by thenbe** [comment]
> Also do you load the plugin first or set the keymap first?

Yup, that was the issue. Good shout.

This fixes it by making `hardtime` load after my keymaps:

```diff
return {
	{
		"m4xshen/hardtime.nvim",
+		event = "VeryLazy",
		opts = {}
	},
}
```

**Comment by m4xshen** [comment]
Thank you very much!

**Comment by directormac** [comment]
> > Also do you load the plugin first or set the keymap first?
> 
> Yup, that was the issue. Good shout.
> 
> This fixes it by making `hardtime` load after my keymaps:
> 
> ```diff
> return {
> 	{
> 		"m4xshen/hardtime.nvim",
> +		event = "VeryLazy",
> 		opts = {}
> 	},
> }
> ```
I tried doing this still j and k with gk and gj rebinding from lazyvim does not trigger hardtime,
 thanks @m4xshen you fixed it finally i mised hardtime for the past few days.
