### ISSUE TITLE
j/k function keymap blocks navigation

### ISSUE THREAD

**Issue by serranomorante** [m4xshen/hardtime.nvim#52]
**Describe the bug**
Out of pure ignorance on my part, why does this keymap work correctly:

```lua
vim.keymap.set({ "n", "x" }, "j", 'v:count || mode(1)[0:1] == "no" ? "j" : "gj"', { noremap = true, expr = true, desc = "Move down by display lines" })
vim.keymap.set({ "n", "x" }, "k", 'v:count || mode(1)[0:1] == "no" ? "k" : "gk"', { noremap = true, expr = true, desc = "Move up by display lines" })
```

while this one completely blocks j/k navigation:

```lua
vim.keymap.set({ "n", "x" }, "j", function()
	return vim.v.count > 0 and "j" or "gj"
end, { noremap = true, expr = true })
vim.keymap.set({ "n", "x" }, "k", function()
	return vim.v.count > 0 and "k" or "gk"
end, { noremap = true, expr = true })
```

Both keymaps work correctly without hardtime.nvim!

**Config options**
- I'm not lazy loading the plugin
- Hardtime is started **after** the keymaps are set
- I use the default configuration

**To Reproduce**
1. Use the second presented keymap
2. Try to navigate with j/k

**Expected behavior**
Both keymaps should be valid to use on hardtime.

**Comment by m4xshen** [comment]
Thanks for the feedback!
