### ISSUE TITLE
Question: disabling notifications in terminal

### ISSUE THREAD

**Issue by b-src** [m4xshen/hardtime.nvim#53]
Hi, I've been using this plugin for a few weeks and enjoying it. I appreciate the hard work you've put into it.

I use the akinsho/toggleterm plugin to open a terminal within neovim, primarily for working with git without having to leave my current window. The problem I'm running into is that I'm getting hardtime alerts while writing commit messages. Is it possible to disable hardtime within the context of the terminal?

**Comment by m4xshen** [comment]
Hardtime.nvim is now disabled when using terminal. Thanks for the feedback!
