### ISSUE TITLE
docs: add vim help file

### ISSUE THREAD

**Issue by m4xshen** [m4xshen/hardtime.nvim#57]
Convert the README.md into vim help file format

**Comment by m4xshen** [comment]
Convert the README.md into vim help file format

**Comment by mikesmithgh** [comment]
Hey @m4xshen I saw your post on Reddit about #hacktoberfest. I'd like to contribute! I think this is a good issue where I can use [panvimdoc](https://github.com/kdheepak/panvimdoc) to generate the vim help files from the README. I have done it before in one of my projects: https://github.com/mikesmithgh/kitty-scrollback.nvim/blob/main/.github/workflows/vimdocs.yml .
