### ISSUE TITLE
Key bindings with Space as <leader> stop working

### ISSUE THREAD

**Issue by milogert** [m4xshen/hardtime.nvim#64]
**Describe the bug**
When the plugin is enabled key bindings that (seemingly) have restricted keys in them stop working properly.

**Config options**
```
require('hardtime').setup({
  restriction_mode = 'hint',
})

vim.g.mapleader = ' '
vim.g.maplocalleader = ' '

vim.cmd [[ nmap <space>h :lua print('Hello')<cr> ]]
```

**To Reproduce**
1. Have the plugin installed.
2. Spam `h`, `j`, `k`, and `l` to make the notification trigger. Keep spamming.
3. Try to use the binding above (`<space>h`).
4. See it doesn't work.

**Expected behavior**
The key binding should work.
 
**Additional context**

**Comment by m4xshen** [comment]
I can't reproduce it. Did you use `:mes` to check whether the message was printed or not?

**Comment by m4xshen** [comment]
@milogert any update?

**Comment by milogert** [comment]
Apologies, last week I got caught up in a project. I'll mess around with this more and if I find something else that doesn't work for me (especially with another plugin) I'll update here.

Thanks and sorry for the late response!
