### ISSUE TITLE
Mouse is not re-enabled when entering buffer with buftype terminal

### ISSUE THREAD

**Issue by mbekkomo** [m4xshen/hardtime.nvim#72]
**Describe the bug**
`hardtime.nvim` does not toggled off when entering buffer with buftype terminal, such as entering `:term`.

**Config options**
None.

**To Reproduce**
1. Open Neovim and have `hardtime.nvim` enabled.
2. Open `buftype=terminal` buffer, such as `:term`.
3. Trying to exit out of Terminal mode by clicking mouse.
4. Stuck.

**Expected behavior**
`hardtime.nvim` are toggled off when entering buffer with buftype terminal.

**Screenshots**
None.

**Additional context**
None.

**Comment by hankertrix** [comment]
For anyone facing this issue, the main problem is that `hardtime.nvim` does not re-enable mouse in the terminal, as `vim.opt.mouse` is still set to `""`, which causes the behaviour described in the issue.

To use the mouse to exit the terminal prompt and scroll through the terminal buffer, you need to re-enable the mouse by setting `vim.opt.mouse = "nvi"` again when in the terminal buffer, which is of course impossible to do when you are stuck in the terminal prompt. Supremely annoying.

Since my pull request (#120) that fixes this issue is still not being merged, you can use the workarounds I use in my configuration, which are listed below. Pick the one you prefer, as either of them will work.

Using auto commands to disable the plugin entirely in terminal mode:
```lua
-- Return the hardtime plugin for lazy.nvim
return {
    "m4xshen/hardtime.nvim",
    dependencies = { "MunifTanjim/nui.nvim", "nvim-lua/plenary.nvim" },

    -- The function to configure the plugin
    config = function(_, opts)
        --

        -- Set up the plugin
        require("hardtime").setup(opts)

        -- Create an auto command group to disable the plugin in terminal mode
        local disable_hardtime_in_terminal_augroup =
            vim.api.nvim_create_augroup(
                "disable_hardtime_in_terminal",
                { clear = true }
            )

        -- Create the auto command to disable the plugin in terminal mode
        vim.api.nvim_create_autocmd("TermOpen", {
            group = disable_hardtime_in_terminal_augroup,
            desc = "Disable hardtime in terminal mode",
            callback = function() vim.cmd("Hardtime disable") end,
        })

        -- Create the auto command to re-enable the plugin
        -- when leaving terminal mode
        vim.api.nvim_create_autocmd("TermClose", {
            group = disable_hardtime_in_terminal_augroup,
            desc = "Re-enable hardtime when leaving terminal mode",
            callback = function() vim.cmd("Hardtime enable") end,
        })
    end,
}
```


Using auto commands to re-enable the mouse in the terminal:
```lua
-- Return the hardtime plugin for lazy.nvim
return {
    "m4xshen/hardtime.nvim",
    dependencies = { "MunifTanjim/nui.nvim", "nvim-lua/plenary.nvim" },

    -- The function to configure the plugin
    config = function(_, opts)
        --

        -- Set up the plugin
        require("hardtime").setup(opts)

        -- Create an auto command group to enable the mouse in terminal mode only
        local enable_mouse_in_terminal_only_augroup =
            vim.api.nvim_create_augroup(
                "enable_mouse_in_terminal_only",
                { clear = true }
            )

        -- Create the auto command to enable the mouse in terminal mode
        vim.api.nvim_create_autocmd("TermOpen", {
            group = enable_mouse_in_terminal_only_augroup,
            desc = "Enable mouse in terminal mode",
            callback = function() vim.opt.mouse = "nvi" end,
        })

        -- Create the auto command to disable the mouse when leaving terminal mode
        vim.api.nvim_create_autocmd("TermClose", {
            group = enable_mouse_in_terminal_only_augroup,
            desc = "Disable mouse when leaving terminal mode",
            callback = function() vim.opt.mouse = "" end,
        })
    end,
}
```

**Comment by hankertrix** [comment]
Alternatively, use the key bind: `<C-\><C-n>` to escape the terminal prompt and enter normal mode.

You can remap this key bind to something that the terminal won't complain about, like `<C-space>`, like this:

```lua
vim.keymap.set("t", "<C-space>", [[<C-\><C-n>]], { desc = "Escape the terminal prompt and enter normal mode" })
```

`[[` and `]]` delimits a raw string in Lua, so the backslash doesn't need to be escaped.

Source: https://reddit.com/r/neovim/comments/yg2d9v/how_do_i_exit_the_terminal_mode/iu6i0kl/
