### ISSUE TITLE
Not picking up j/k repeating when using LazyVim distro

### ISSUE THREAD

**Issue by JamesMowery** [m4xshen/hardtime.nvim#74]
Repeated h/j key presses are not being picked up when using LazyVim. Any advice on how to resolve?

**Comment by JamesMowery** [comment]
I was able to resolve by doing the following in my hardtime.lua plugin:

```
return {
  "m4xshen/hardtime.nvim",
  command = "Hardtime",
  event = "BufEnter",
  dependencies = {
    "MunifTanjim/nui.nvim",
    "nvim-lua/plenary.nvim",
  },
  keys = {
    { "j", 'v:count || mode(1)[0:1] == "no" ? "j" : "gj"' },
    { "k", 'v:count || mode(1)[0:1] == "no" ? "k" : "gk"' },
  },
  opts = {},
}

```

Is there any other change to LazyVim I need to make to ensure no conflicts?

**Comment by JamesMowery** [comment]
Update: The above change actually did not resolve the issue. Getting the following issue with this box popping up on LazyVim when using j / k in a file.

![Screenshot_20240120_225153](https://github.com/m4xshen/hardtime.nvim/assets/868178/a2e7b5c3-c22f-4363-9772-04a72ffe8095)

**Comment by m4xshen** [comment]
> v:count || mode(1)[0:1] == "no" ? "j" : "gj"

This kind of mapping only work for Vim-style mapping when using `:map`. For Lua you should convert this into a function.

Example:
```lua
vim.keymap.set({ "n", "x" }, "j", function()
   return vim.v.count > 0 and "j" or "gj"
end, { noremap = true, expr = true })
vim.keymap.set({ "n", "x" }, "k", function()
   return vim.v.count > 0 and "k" or "gk"
end, { noremap = true, expr = true })
```

**Comment by spa5k** [comment]
For someone coming to this later on, this works without problem - 

```lua
    {
        'm4xshen/hardtime.nvim',
        dependencies = { 'MunifTanjim/nui.nvim', 'nvim-lua/plenary.nvim' },
        opts = {},
        command = 'Hardtime',
        event = 'BufEnter',
        keys = {
            { 'n', 'j',  '<cmd>Hardtime<CR>', desc = "Hardtime" },
            { 'n', 'k',  '<cmd>Hardtime<CR>', desc = "Hardtime" },
            { 'n', 'gj', '<cmd>Hardtime<CR>', desc = "Hardtime" },
            { 'n', 'gk', '<cmd>Hardtime<CR>', desc = "Hardtime" },
        },
    },
    ```

**Comment by jyeharry** [comment]
@spa5k I this actually maps the "n" key to gk. You're fix worked for me until I searched for something and pressed n to cycle through the occurrences, but instead my cursor was just moving up the screen. It did fix j and k not working though, but I don't think it fixed it for the reason we thought it would and since n is now broken I don't think its an ideal fix.

**Comment by jyeharry** [comment]
I've got this in my config:
```
return {
  {
    "m4xshen/hardtime.nvim",
    dependencies = { "MunifTanjim/nui.nvim" },
    opts = {},
    command = "Hardtime",
    event = "VeryLazy",
    keys = {
      {
        "j",
        function()
          return vim.v.count > 0 and "j" or "gj"
        end,
        mode = { "n", "x" },
      },
      {
        "k",
        function()
          return vim.v.count > 0 and "k" or "gk"
        end,
        mode = { "n", "x" },
      },
    },
  },
}
```
However this only seems to work after I open a second file. Upon running `nvim some/file` the plugin doesn't work and the j and k keys are unresponsive. After opening a second file it all works as expected. Any suggestions @m4xshen?

**Comment by jyeharry** [comment]
This is my fix:
```
return {
  {
    "m4xshen/hardtime.nvim",
    dependencies = { "MunifTanjim/nui.nvim" },
    opts = {},
    keys = {
      {
        "j",
        function()
          vim.cmd("Hardtime enable")
          return vim.v.count > 0 and "j" or "gj"
        end,
        mode = { "n", "x" },
      },
      {
        "k",
        function()
          vim.cmd("Hardtime enable")
          return vim.v.count > 0 and "k" or "gk"
        end,
        mode = { "n", "x" },
      },
    },
  },
}
```

The first press of j or k doesn't do anything, after that they work as normal until blocked by hardtime. I feel like there should be a simpler fix though. Unfortunately I'm not super familiar with exactly how to setup plugins the lazy.nvim way and since this works I'm just gonna stick with it for now.

**Comment by jyeharry** [comment]
[This solution](https://github.com/m4xshen/hardtime.nvim/issues/31#issuecomment-1685762701) works. It's pretty the same solution originally provided by @JamesMowery however it may be because this solution has `lazy = false` in it.
