### ISSUE TITLE
hardtime ignores keys mapped to hjkl

### ISSUE THREAD

**Issue by flexagoon** [m4xshen/hardtime.nvim#79]
**Describe the bug**
If I remap some key to h/j/k/l, hardtime doesn't restrict that key

**Config options**
Default config

**To Reproduce**
1. `:nnoremap <Down> j`
2. Try to spam the down arrow

**Expected behavior**
The down arrow is treated as the "j" key and is restricted by hardtime

**Comment by m4xshen** [comment]
@flexagoon did you try mapping key like this https://github.com/m4xshen/hardtime.nvim/issues/31#issuecomment-1685762701 ?

**Comment by declancm** [comment]
You can use `:nmap <down> j` to use the existing j mapping
