### ISSUE TITLE
Neoscroll compatability

### ISSUE THREAD

**Issue by olivertzeng** [m4xshen/hardtime.nvim#86]
**Describe the bug**
when scrolling with [NeoScroll](https://github.com/karb94/neoscroll.nvim) it says
> The <Up/Down> key is disabled!

**Config options**
		opts = {},

**To Reproduce**
1. Install neoscroll
2. Start scrolling

**Expected behavior**
scroll

**Comment by m4xshen** [comment]
Hi, could you please explain which scrolling method is blocked? I just tried `<C-u>`, `<C-d>`, `<C-b>`, `<C-f>`, `<C-y>`, `<C-e>`, `zt`, `zz`, `zb` and they works fine with neoscroll.nvim.

**Comment by olivertzeng** [comment]
> Hi, could you please explain which scrolling method is blocked? I just tried `<C-u>`, `<C-d>`, `<C-b>`, `<C-f>`, `<C-y>`, `<C-e>`, `zt`, `zz`, `zb` and they work fine with neoscroll.nvim.

scrolling with the mouse or with the trackpad/touchpad

**Comment by olivertzeng** [comment]
> hardtime.nvim disables mouse by default. You can enable it with this option:
> 
> ```lua
> disable_mouse = false,
> ```

thanks bro
