### ISSUE TITLE
Use D instead of d$ and Y instead of y$

### ISSUE THREAD

**Issue by olivertzeng** [m4xshen/hardtime.nvim#90]

**Comment by m4xshen** [comment]
You can add hints inside [config.lua](https://github.com/m4xshen/hardtime.nvim/blob/main/lua/hardtime/config.lua#L93) following the structure of [hint example](https://github.com/m4xshen/hardtime.nvim?tab=readme-ov-file#hints-example).

By the way `H` is different from `gg`.

**Comment by olivertzeng** [comment]
Thanks!
 Sent from Proton Mail for iOS 
於 週二, 4月 23, 2024 時間 14:35, Max Shen ***@***.***&gt; 寫道：  You can add hints inside config.lua following the structure of hint example.
By the way H is different from gg.
