### ISSUE TITLE
`ddO` being warned "Use o instead of jO"

### ISSUE THREAD

**Issue by olivertzeng** [m4xshen/hardtime.nvim#93]
>    Warn  07時03分37秒 notify.warn hardtime Use o instead of jO

probably the same problem as #77 should I actually close this issue and comment on that thread

because i think that `2ddO` is just `djO`

**Comment by m4xshen** [comment]
Sorry I can't reproduce this warning. Do you have any mapping related to `d`?

**Comment by olivertzeng** [comment]
> Sorry I can't reproduce this warning. Do you have any mapping related to `d`?

hmm weird, on my side sometimes works sometimes doesnt

probably my issue will close this
